calendar_scheduler/core/urls.py
__author__ = 'Konstantin Oficerov'
__email__ = 'konstantin.oficerov@gmail.com'
from django.conf.urls import patterns, include, url
from views import *
from api import *

urlpatterns = patterns('',
                       url(r'^home/$', FeedbackHandler.as_view(), name="home"),
                       url(r'^calendar/$', CalendarHandler.as_view(), name="calendar"),
                       url(r'^api/$', BaseCalendarAPI.as_view(), name='calendar-api')
                      )

scheduler/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'calendar_scheduler.views.main_view', name='gateway'),
                       url(r'^scheduler/', include('calendar_scheduler.core.urls', namespace='calendar_scheduler')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       # Authentication with google account

                       url(r'^(google/)?login/$', 'django_openid_auth.views.login_begin', name='openid-login'),
                       url(r'^google/login-complete/$', 'django_openid_auth.views.login_complete',
                           name='openid-complete'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/', }, name='logout'),
                       ) + staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--><html lang="en"><!--<![endif]-->

<head>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
{% load static %}
<!-- Bootstrap Stylesheet -->
<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}" media="all">

<!-- jquery-ui Stylesheets -->
<link rel="stylesheet" href="{% static "assets/jui/css/jquery-ui.css"%}" media="screen">

<link rel="stylesheet" href="{% static "assets/jui/jquery-ui.custom.css"%}" media="screen">
<link rel="stylesheet" href="{% static "assets/jui/timepicker/jquery-ui-timepicker.css"%}" media="screen">

<!-- Uniform Stylesheet -->
<link rel="stylesheet" href="{% static "plugins/uniform/css/uniform.default.css"%}" media="screen">

<!-- Main Layout Stylesheet -->
<link rel="stylesheet" href="{% static "assets/css/fonts/icomoon/style.css"%}" media="screen">
<link rel="stylesheet" href="{% static "assets/css/main-style.css"%}" media="screen">
{% block media_css %}{% endblock %}

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<title>{% block title %}Welcome to your personal schedule, {{ request.user }}!{% endblock %}</title>

</head>

<body data-show-sidebar-toggle-button="true" data-fixed-sidebar="false">
    <!--
    <div id="customizer">
        <div id="showButton"><i class="icon-cogs"></i></div>
        <div id="layoutMode">
            <label class="checkbox"><input type="checkbox" class="uniform" name="layout-mode" value="boxed"> Boxed</label>
        </div>
    </div>
    -->
    <div id="locker" style="display: none">
        <img src="{% static "assets/images/preloaders/15.gif" %}"/>
    </div>
    <div id="wrapper">
        <header id="header" class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
					<div class="brand-wrap pull-left">
						<div class="brand-img">
							<a class="brand">
								<img src="{% static "assets/images/logo_scheduler.png"%}" alt="" style="width: 117px; height: 21px;">
							</a>
						</div>
					</div>
                    
                    <div id="header-right" class="clearfix">
						<!-- Notification Search and Message in MoonCake template -->
                        <div id="header-functions" class="pull-right">
                        	<div id="user-info" class="clearfix">
                                <span class="info">
                                	Welcome
                                    <span class="name">{{ request.user }}</span>
                                </span>
                            	<div class="avatar">
                                	<a class="dropdown-toggle" href="#">
                                    	<!-- <img src="assets/images/pp.jpg" alt="Avatar"> Replace to default / media file-->
                                    </a>
                                </div>
                            </div>
                            <div id="logout-ribbon">
                            	<a href="{% url "logout" %}"><i class="icon-off"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        <div id="content-wrap">
        	<div id="content">
            	<div id="content-outer">
                	<div id="content-inner">
                    	<aside id="sidebar">
                        	<nav id="navigation" class="collapse">
                            	<ul>
                                	<li>
                                    	<span class="nav-general" title="General">
                                    		<i class="icon-home"></i>
											<span class="nav-title">General</span>
                                        </span>
                                    	<ul class="inner-nav">
                                           <li><a class="tab-dashboard" href="{% url "calendar_scheduler:home" %}"><i class="icol-feed"></i> Feedback</a></li>
                                           <li><a class="tab-calendar" href="{% url "calendar_scheduler:calendar" %}"><i class="icol-calendar-1"></i> Calendar</a></li>
                                        </ul>
                                    </li>
                                	<li>
                                    	<span class="nav-settings" title="Elements">
                                        	<i class="icon-cogs"></i>
											<span class="nav-title">Settings</span>
                                        </span>
                                    	<ul class="inner-nav">
                                        	<li>
                                                <a class="tab-example">
                                                    <i class="icol-ui-tab-content"></i> Nothing
                                                </a>
                                            </li>
                                            {% if request.user.is_staff %}
                                            <li>
                                                <a target="_blank" class="tab-admin" href="{% url 'admin:index' %}">
                                                    <i class="icol-user-business-boss"></i> Administration
                                                </a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </li>

                                </ul>
                            </nav>
                        </aside>

                        <div id="sidebar-separator"></div>
                        
                        <section id="main" class="clearfix">
                        	<div id="main-header" class="page-header">
                            	<!--
                                <h1 id="main-heading">
                                	Calendar <span>This page shows off some usage examples of the FullCalendar plugin</span>
                                </h1>
                                -->
                            </div>
                            
                            <div id="main-content">
                            	<div class="row-fluid">                                    
                                	<div class="span12 widget" id="content-block">
                                        {% block content %}{% endblock %}
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
        
        <footer id="footer">
            <div class="footer-left">Calendar scheduler.</div>
            <div class="footer-right"><p>Copyright 2014. All Rights Reserved.</p></div>
        </footer>
        
    </div>

	<!-- Core Scripts -->
	<script src="{% static "assets/js/libs/jquery-1.8.3.min.js" %}"></script>
	<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
	<script src="{% static "assets/js/libs/jquery.placeholder.min.js" %}"></script>
	<script src="{% static "assets/js/libs/jquery.mousewheel.min.js" %}"></script>
    
    <!-- Template Script -->
    <script src="{% static "assets/js/template.js" %}"></script>
    <script src="{% static "assets/js/setup.js" %}"></script>

    <!-- Customizer, remove if not needed -->
    <!-- <script src="{% static "assets/js/customizer.js" %}"></script> -->

    <!-- Uniform Script -->
    <script src="{% static "plugins/uniform/jquery.uniform.min.js" %}"></script>
    
    <!-- jquery-ui Scripts -->
    <script src="{% static "assets/jui/js/jquery-ui-1.9.2.min.js" %}"></script>
    <script src="{% static "assets/jui/jquery-ui.custom.min.js" %}"></script>
    <script src="{% static "assets/jui/timepicker/jquery-ui-timepicker.min.js" %}"></script>
	<script src="{% static "assets/jui/jquery.ui.touch-punch.min.js" %}"></script>

    <script language="JavaScript">
        (function($, document, window){
            window.locker = $('#locker');
            window.lock = function(){window.locker.show()};
            window.unlock = function(){window.locker.hide()};
            var active_bar = $('nav#navigation').find($('span.nav-{% block nav-name %}{% endblock %}'));
            if(active_bar.length){
                active_bar.parent().addClass('active open');
            }
            var active_tab = $('ul.inner-nav').find($('a.tab-{% block tab-name %}{% endblock %}'));
            if(active_tab.length){
                active_tab.parent().addClass('active');
            }
        })(jQuery, document, window)
    </script>
    {% block media_js %}{% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base.html' %}

{% block content %}
    {% load wtforms %}
    <div class="widget-content">
        <div id="calendar-content"></div>
    </div>
    <div id="modalForm" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Modal header</h3>
      </div>
      <div class="modal-body">
          <div class="form-container">
          <form id="main-form" method="post">
              {% csrf_token %}
              {% form_field form.owner %}
              <div class="control-group">
                  <label>
                      Event title:
                  </label>
                  <div class="controls">
                      {% form_field form.title class="span12" %}
                  </div>
              </div>
              <div class="control-group">
                  <div class="controls-row">
                      <div class="span6">

                          <div class="controls">
                              <label>
                                  Event begins at:
                              </label>
                              {% form_field form.start class="span12" %}
                          </div>
                      </div>
                      <div class="span6">

                          <div class="controls">
                              <label>
                                  Event finish at:
                              </label>
                              {% form_field form.end class="span12"%}
                          </div>
                      </div>
                  </div>
              </div>
              <div class="control-group">
                  <div class="controls-row">
                      <div class="span6">
                          <div class="controls">
{#                              <label>#}
{#                                  All day:#}
{#                              </label>#}
                                {% form_field form.allDay %}
                          </div>
                      </div>
                      <div class="span6">
                          <div class="controls">
{#                              <label>#}
{#                                  Private:#}
{#                              </label>#}
                              {% form_field form.privateMode %}
                          </div>
                      </div>
                  </div>
              </div>
              <div class="control-group">
                  <label>
                      Color:
                  </label>
                  <div class="controls">
                      {% form_field form.color %}
                  </div>
              </div>
              <div class="control-group">
                  <label>
                      Description:
                  </label>
                  <div class="controls">
                      {% form_field form.description  class="span12" %}
                  </div>
              </div>
              <div class="control-group">
                  {% form_field form.guests class="span12"%}
              </div>
          </form>
          </div>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button id="save-btn" type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
{% endblock %}

{% block nav-name %}general{% endblock %}
{% block tab-name %}calendar{% endblock %}
{% block media_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'plugins/fullcalendar/fullcalendar.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'plugins/fullcalendar/fullcalendar.print.css' %}" media="print"/>
    <link rel="stylesheet" href="{% static 'plugins/ibutton/jquery.ibutton.css' %}" media="all"/>
    <link rel="stylesheet" href="{% static 'application-plugins/css/scheduler-main.css' %}" media="all"/>
    <link id="preloader2" rel="image" href="{% static 'assets/images/preloaders/2.gif' %}"/>
    <link rel="stylesheet" href="{% static 'custom-plugins/Select2-3.4.8/select2-bootstrap.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'custom-plugins/Select2-3.4.8/select2.css' %}" media="screen"/>
{% endblock %}
{% block media_js %}
    <script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'plugins/ibutton/jquery.ibutton.min.js' %}"></script>
    <script src="{% static 'assets/js/libs/jquery.cookie.js' %}"></script>
    <script src="{% static 'custom-plugins/Select2-3.4.8/select2.min.js' %}"></script>
    <script language="JavaScript">
        $(document).ready(function() {
            // page is now ready, initialize the calendar...
            console.log('calendar now is loading');

            document.API = {
                url: '{%url "calendar_scheduler:calendar-api" %}',
                filter_owner: 'all',
                csrf_token: $.cookie('csrftoken'),
                user_pk: {{ request.user.pk }}
            };

        });
    </script>
    <script src="{% static 'application-plugins/js/calendar.js' %}"></script>
{% endblock %}

templates/feed.html
{% extends 'base.html' %}

{% block content %}
    {% if feed %}
    <!-- do something -->
    {% else %}
        <div class="widget-content">
            <div class="alert alert-block alert-info">
                <i class="icon-info-sign"></i> There is no news yet.
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block nav-name %}general{% endblock %}
{% block tab-name %}dashboard{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}